#!/bin/bash

set -e
#set -x

################################################################################
########################################################################################################################
################################################################################

SCRIPTDIR=$(dirname "$0")
SCRIPTDIR=$(cd ${SCRIPTDIR} && pwd)
SCRIPTDIR="${SCRIPTDIR}/.scripts"

OUTDIR="/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive"
MIRROR="1"
COMBINED="1"

while getopts ":o:mc" opt; do
	case $opt in
		o) OUTDIR="$OPTARG" ;;
		m) MIRROR="0" ;;
		c) COMBINED="0" ;;
		\?) echo "Invalid option: -$OPTARG" >&2 && exit 1 ;;
		:) echo "Option -$OPTARG requires an argument." >&2 && exit 1 ;;
	esac
done

[ -d "$(dirname ${OUTDIR})" ] || exit 1

rm -Rf ${OUTDIR}/openmediavault

################################################################################
########################################################################################################################
################################################################################

if [ "${MIRROR}" == "0" ]; then
	
	${SCRIPTDIR}/mirror_repository \
		-d "${OUTDIR}/.openmediavault-mirror" \
		-u "http://packages.openmediavault.org/public" \
		-s "stoneburner" \
		-c "main" \
		-a "amd64 i386"
	
	
	${SCRIPTDIR}/mirror_repository \
		-d "${OUTDIR}/.omvextras-mirror" \
		-u "http://omv-extras.org/debian" \
		-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
		-c "main" \
		-a "amd64 i386"

fi

################################################################################
########################################################################################################################
################################################################################

rm -Rf ${OUTDIR}/.openmediavault-build

${SCRIPTDIR}/build_package \
	-o "${OUTDIR}/.openmediavault-build" \
	-s "stoneburner" \
	-c "main" \
	-p "openmediavault" \
	-b "master"	

#${SCRIPTDIR}/build_package \
#	-o "${OUTDIR}/.openmediavault-build" \
#	-s "stoneburner" \
#	-c "main" \
#	-p "openmediavault-keyring" \
#	-b "master"

${SCRIPTDIR}/build_package \
	-o "${OUTDIR}/.openmediavault-build" \
	-s "stoneburner" \
	-c "testing" \
	-p "openmediavault" \
	-b "testing"	

#${SCRIPTDIR}/build_package \
#	-o "${OUTDIR}/.openmediavault-build" \
#	-s "stoneburner" \
#	-c "testing" \
#	-p "openmediavault-keyring" \
#	-b "testing"

################################################################################

rm -Rf ${OUTDIR}/.omvextras-build

${SCRIPTDIR}/build_package \
	-o "${OUTDIR}/.omvextras-build" \
	-s "stoneburner" \
	-c "main" \
	-p "openmediavault-omvextrasorg" \
	-b "master"

${SCRIPTDIR}/build_package \
	-o "${OUTDIR}/.omvextras-build" \
	-s "stoneburner" \
	-c "main" \
	-p "openmediavault-ddclient" \
	-b "master"

${SCRIPTDIR}/build_package \
	-o "${OUTDIR}/.omvextras-build" \
	-s "stoneburner-testing" \
	-c "main" \
	-p "openmediavault-dnsmasq" \
	-b "master"

${SCRIPTDIR}/build_package \
	-o "${OUTDIR}/.omvextras-build" \
	-s "stoneburner" \
	-c "testing" \
	-p "openmediavault-omvextrasorg" \
	-b "testing"

${SCRIPTDIR}/build_package \
	-o "${OUTDIR}/.omvextras-build" \
	-s "stoneburner" \
	-c "testing" \
	-p "openmediavault-ddclient" \
	-b "testing"

${SCRIPTDIR}/build_package \
	-o "${OUTDIR}/.omvextras-build" \
	-s "stoneburner-testing" \
	-c "testing" \
	-p "openmediavault-dnsmasq" \
	-b "testing"

################################################################################
########################################################################################################################
################################################################################

${SCRIPTDIR}/copy_packages \
	-d "${OUTDIR}/openmediavault" \
	-i "${OUTDIR}/.openmediavault-mirror ${OUTDIR}/.openmediavault-build" \
	-n "openmediavault" \
	-s "stoneburner" \
	-c "main" \
	-a "amd64 i386" \
	-r

${SCRIPTDIR}/copy_packages \
	-d "${OUTDIR}/openmediavault" \
	-i "${OUTDIR}/.openmediavault-mirror ${OUTDIR}/.openmediavault-build" \
	-n "openmediavault" \
	-s "stoneburner" \
	-c "main" \
	-k "testing" \
	-a "amd64 i386"

${SCRIPTDIR}/copy_packages \
	-d "${OUTDIR}/openmediavault" \
	-i "${OUTDIR}/.openmediavault-mirror ${OUTDIR}/.openmediavault-build" \
	-n "openmediavault" \
	-s "stoneburner" \
	-c "testing" \
	-a "amd64 i386"

################################################################################

rm -Rf ${OUTDIR}/openmediavault

if [ "${COMBINED}" == "0" ]; then
	
	${SCRIPTDIR}/copy_packages \
		-d "${OUTDIR}/openmediavault" \
		-i "${OUTDIR}/.omvextras-mirror ${OUTDIR}/.omvextras-build" \
		-n "omvextras" \
		-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
		-z "stoneburner" \
		-c "main" \
		-a "amd64 i386" \
		-r
	
	${SCRIPTDIR}/copy_packages \
		-d "${OUTDIR}/openmediavault" \
		-i "${OUTDIR}/.omvextras-mirror ${OUTDIR}/.omvextras-build" \
		-n "omvextras" \
		-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
		-z "stoneburner" \
		-c "main" \
		-k "testing" \
		-a "amd64 i386"
	
	${SCRIPTDIR}/copy_packages \
		-d "${OUTDIR}/openmediavault" \
		-i "${OUTDIR}/.omvextras-mirror ${OUTDIR}/.omvextras-build" \
		-n "omvextras" \
		-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
		-z "stoneburner" \
		-c "testing" \
		-a "amd64 i386"
	
else
	
	rm -Rf ${OUTDIR}/omvextras
	
	${SCRIPTDIR}/copy_packages \
		-d "${OUTDIR}/omvextras" \
		-i "${OUTDIR}/.omvextras-mirror ${OUTDIR}/.omvextras-build" \
		-n "omvextras" \
		-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
		-c "main" \
		-a "amd64 i386" \
		-r
	
	${SCRIPTDIR}/copy_packages \
		-d "${OUTDIR}/omvextras" \
		-i "${OUTDIR}/.omvextras-mirror ${OUTDIR}/.omvextras-build" \
		-n "omvextras" \
		-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
		-c "main" \
		-k "testing" \
		-a "amd64 i386"
	
	${SCRIPTDIR}/copy_packages \
		-d "${OUTDIR}/omvextras" \
		-i "${OUTDIR}/.omvextras-mirror ${OUTDIR}/.omvextras-build" \
		-n "omvextras" \
		-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
		-c "testing" \
		-a "amd64 i386"
	
fi

################################################################################
########################################################################################################################
################################################################################

if [ "${COMBINED}" == "0" ]; then
	
	${SCRIPTDIR}/debarchive_repository \
		-d "${OUTDIR}/openmediavault" \
		-g "${OUTDIR}/.gnupg" \
		-n "openmediavault" \
		-s "stoneburner" \
		-c "main" \
		-a "amd64 i386" \
		-r
	
	${SCRIPTDIR}/debarchive_repository \
		-d "${OUTDIR}/openmediavault" \
		-g "${OUTDIR}/.gnupg" \
		-n "openmediavault" \
		-s "stoneburner" \
		-c "testing" \
		-a "amd64 i386" \
		-r
	
else
	
	${SCRIPTDIR}/debarchive_repository \
		-d "${OUTDIR}/openmediavault" \
		-g "${OUTDIR}/.gnupg" \
		-n "openmediavault" \
		-s "stoneburner" \
		-c "main" \
		-a "amd64 i386" \
		-r
	
	${SCRIPTDIR}/debarchive_repository \
		-d "${OUTDIR}/openmediavault" \
		-g "${OUTDIR}/.gnupg" \
		-n "openmediavault" \
		-s "stoneburner" \
		-c "testing" \
		-a "amd64 i386" \
		-r
	
	
	${SCRIPTDIR}/debarchive_repository \
		-d "${OUTDIR}/omvextras" \
		-g "${OUTDIR}/.gnupg" \
		-n "omvextras" \
		-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
		-c "main" \
		-a "amd64 i386" \
		-r
	
	${SCRIPTDIR}/debarchive_repository \
		-d "${OUTDIR}/omvextras" \
		-g "${OUTDIR}/.gnupg" \
		-n "omvextras" \
		-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
		-c "testing" \
		-a "amd64 i386" \
		-r
	
fi

################################################################################
########################################################################################################################
################################################################################

echo "[ DONE ]"
exit 0

################################################################################
########################################################################################################################
################################################################################
