#!/bin/bash

set -e
#set -x

DIRNAME=$(dirname "$0")
DIRNAME=$(cd ${DIRNAME} && pwd)
DIRNAME="${DIRNAME}/.scripts"

################################################################################
# Copy Repository

OUTDIR=${1:-"/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive"}
[ -d "$(dirname ${OUTDIR})" ] || exit 1

${DIRNAME}/openmediavault_mirror "${OUTDIR}/.openmediavault-mirror"
${DIRNAME}/omvextras_mirror "${OUTDIR}/.omvextras-mirror"

${DIRNAME}/openmediavault_build "${OUTDIR}/.openmediavault-build"
${DIRNAME}/omvextras_build "${OUTDIR}/.omvextras-build"

${DIRNAME}/openmediavault_copy "${OUTDIR}/openmediavault" "${OUTDIR}/.openmediavault-mirror" "${OUTDIR}/.openmediavault-build"
${DIRNAME}/omvextras_copy "${OUTDIR}/omvextras" "${OUTDIR}/.omvextras-mirror" "${OUTDIR}/.omvextras-build"

${DIRNAME}/openmediavault_debarchive "${OUTDIR}/openmediavault"
${DIRNAME}/omvextras_debarchive "${OUTDIR}/omvextras"


################################################################################

exit 0

################################################################################
