#!/bin/bash

set -e
#set -x

export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

SCRIPTNAME=$(basename "$0")

################################################################################
## Need Packages

NEEDEDPACKAGES=""
if [ -z `which dch` ]; then NEEDEDPACKAGES+="devscripts "; fi
if [ -z `which make` ]; then NEEDEDPACKAGES+="build-essential "; fi
if [ -z `which dh_builddeb` ]; then NEEDEDPACKAGES+="git-core "; fi
if [ -z `which git` ]; then NEEDEDPACKAGES+="debhelper "; fi
if [ -n "${NEEDEDPACKAGES}" ]; then
	echo "Need ${NEEDEDPACKAGES}, installing them..."
	apt-get -qq -y install ${NEEDEDPACKAGES}
fi

################################################################################
## Need TEMPDIR

TEMPDIR=$(mktemp -d -t ${SCRIPTNAME}.XXXXXXXXXX)
LOCKFILE=${TEMPDIR}/${SCRIPTNAME}.lock
[ -f "${LOCKFILE}" ] && echo "ERROR ${LOCKFILE} already exist. !!!" && exit 255

################################################################################
## Need CleanUp

function clean_up() {
	
	#echo "Clean up ..."
	rm -Rf "${TEMPDIR}"
	
	if [ "$1" != "0" ]; then
		echo "ERROR ..."
		exit $1
	else
		#echo " -> Done ..."
		exit 0
	fi
}

function print_help() {
	echo "
${SCRIPTNAME}  version 0.1b
Copyright (C) 2015 by Simon Baur (sbausis at gmx dot net)

Usage: ${SCRIPTNAME} [OPTIONS]... -o [OUTFILE]

Options
 -s,  --suite                 set Suite
 -c,  --component             set Component
"
}

function help_exit() {
	print_help
	clean_up 1
}

################################################################################

function _build_package() {
	local BUILDDIR="$1"
	local PACKAGE="$2"
	local BRANCH=${3:-"main"}
	
	[ -d "${BUILDDIR}" ] || mkdir -p "${BUILDDIR}" &>/dev/null
	[ -d "${BUILDDIR}/${PACKAGE}" ] && rm -Rf "${BUILDDIR}/${PACKAGE}" &>/dev/null
	[ -f "${BUILDDIR}/${PACKAGE}*.deb" ] && rm -f "${BUILDDIR}/${PACKAGE}*.deb" &>/dev/null
	
	git clone -b ${BRANCH} https://github.com/sbausis/${PACKAGE}.git "${BUILDDIR}/${PACKAGE}" &>/dev/null
	
	set +e
	(cd "${BUILDDIR}/${PACKAGE}" && git submodule init &>/dev/null)
	(cd "${BUILDDIR}/${PACKAGE}" && git submodule update &>/dev/null)
	(cd "${BUILDDIR}/${PACKAGE}" && dpkg-buildpackage -b &>/dev/null)
	set -e
	
	[ -f ${BUILDDIR}/${PACKAGE}*.deb ] && ls ${BUILDDIR}/${PACKAGE}*.deb
}
function build_package() {
	local BUILDDIR="$1"
	local SUITE="$2"
	local COMP="$3"
	
	local PACKAGE="$4"
	local BRANCH=${5:-"main"}
	
	local COMPDIR="${BUILDDIR}/${SUITE}/${COMP}"
	local REMOTE_REF=$(git ls-remote https://github.com/sbausis/${PACKAGE}.git | grep "refs/heads/${BRANCH}" | awk '{print $1}')
	local LOCAL_REF=$([ -f "${COMPDIR}/${PACKAGE}_${BRANCH}.ref" ] && cat "${COMPDIR}/${PACKAGE}_${BRANCH}.ref")
	
	if [ -z "${LOCAL_REF}" ] || [ "${LOCAL_REF}" != "${REMOTE_REF}" ]; then
		
		echo "[ ${SCRIPTNAME} ] ${PACKAGE} ${BRANCH}"
		
		local PKGFILE=$(_build_package "${TEMPDIR}/${PACKAGE}-${BRANCH}" "${PACKAGE}" "${BRANCH}")
		local PKGARCH=$(echo "${PKGFILE}" | sed 's/.*_\(.*\).deb/\1/')
		local PKGDIR="${COMPDIR}/${PKGARCH}/${PACKAGE:0:1}/${PACKAGE}"
		echo "  - ${PKGFILE} ${PKGARCH} -> ${PKGDIR}"
		
		[ -d "${PKGDIR}" ] || mkdir -p ${PKGDIR} &>/dev/null
		[ -f ${PKGDIR}/${PACKAGE}*.deb ] && rm -f ${PKGDIR}/${PACKAGE}*.deb &>/dev/null
		cp -fv 	${TEMPDIR}/${PACKAGE}-${BRANCH}/${PACKAGE}*.deb ${PKGDIR}/
		
		echo "${LOCAL_REF}" > "${COMPDIR}/${PACKAGE}_${BRANCH}.bkp"
		echo "${REMOTE_REF}" > "${COMPDIR}/${PACKAGE}_${BRANCH}.ref"
		
	else
		rm -f "${COMPDIR}/${PACKAGE}_${BRANCH}.bkp"
		echo "[ ${SCRIPTNAME} ] ${PACKAGE} ${BRANCH} already up to date ..."
		
	fi
	
	
}

################################################################################
## Need LOCKFILE

trap "{ clean_up; exit 255; }" SIGHUP SIGINT SIGTERM SIGQUIT
touch ${LOCKFILE}

################################################################################
## Need Arguments

#BUILDDIR="/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive_build"
#SUITE="$3"
#COMP="$4"
#PACKAGE="$5"
#BRANCH="$6"

while getopts ":o:s:c:p:b:" opt; do
	case $opt in
		o) BUILDDIR="$OPTARG" ;;
		s) SUITE="$OPTARG" ;;
		c) COMP="$OPTARG" ;;
		p) PACKAGE="$OPTARG" ;;
		b) BRANCH="$OPTARG" ;;
		\?) echo "Invalid option: -$OPTARG" >&2 && help_exit ;;
		:) echo "Option -$OPTARG requires an argument." >&2 && help_exit ;;
	esac
done

if [ -z "${BUILDDIR}" ] && [ -z "${SUITE}" ] && [ -z "${COMP}" ] && [ -z "${PACKAGE}" ] && [ -z "${BRANCH}" ]; then
	help_exit
fi

################################################################################

#echo "[ ${SCRIPTNAME} ] ${PACKAGE} ${BRANCH}"

build_package "${BUILDDIR}" "${SUITE}" "${COMP}" "${PACKAGE}" "${BRANCH}"

clean_up 0

################################################################################
