#!/bin/bash

set -e
#set -x

DIRNAME=$(dirname "$0")

################################################################################
# Copy Repository

OUTDIR=${1:-"/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive/openmediavault"}
[ -d "$(dirname ${OUTDIR})" ] || exit 1

################################################################################

${DIRNAME}/debarchive_repository \
	-d "${OUTDIR}" \
	-g "${OUTDIR}/../.gnupg" \
	-n "omvextras" \
	-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
	-c "main" \
	-a "amd64 i386" \
	-r

${DIRNAME}/debarchive_repository \
	-d "${OUTDIR}" \
	-g "${OUTDIR}/../.gnupg" \
	-n "omvextras" \
	-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
	-c "testing" \
	-a "amd64 i386" \
	-r

################################################################################

exit 0

################################################################################
