#!/bin/bash

set -e
#set -x

DIRNAME=$(dirname "$0")

################################################################################
# Copy Repository

OUTDIR=${1:-"/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive_build/omvextras"}
[ -d "$(dirname ${OUTDIR})" ] || exit 1

################################################################################

${DIRNAME}/build_package -o "${OUTDIR}" \
							-s "stoneburner" -c "main" \
							-p "openmediavault-omvextrasorg" -b "master"

${DIRNAME}/build_package -o "${OUTDIR}" \
							-s "stoneburner" -c "main" \
							-p "openmediavault-ddclient" -b "master"

${DIRNAME}/build_package -o "${OUTDIR}" \
							-s "stoneburner-testing" -c "main" \
							-p "openmediavault-dnsmasq" -b "master"

################################################################################

${DIRNAME}/build_package -o "${OUTDIR}" \
							-s "stoneburner" -c "testing" \
							-p "openmediavault-omvextrasorg" -b "testing"

${DIRNAME}/build_package -o "${OUTDIR}" \
							-s "stoneburner" -c "testing" \
							-p "openmediavault-ddclient" -b "testing"

${DIRNAME}/build_package -o "${OUTDIR}" \
							-s "stoneburner-testing" -c "testing" \
							-p "openmediavault-dnsmasq" -b "testing"

################################################################################

exit 0

################################################################################
