#!/bin/bash

set -e
#set -x

DIRNAME=$(dirname "$0")

################################################################################
# Copy Repository

OUTDIR=${1:-"/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive_input/omvextras"}
[ -d "$(dirname ${OUTDIR})" ] || exit 1

################################################################################

${DIRNAME}/mirror_repository \
	-d "${OUTDIR}" \
	-u "http://omv-extras.org/debian" \
	-s "stoneburner stoneburner-backports stoneburner-beta stoneburner-btsync stoneburner-docker-testing stoneburner-docker stoneburner-dotdeb stoneburner-gluster stoneburner-greyhole stoneburner-hwraid stoneburner-mono-testing stoneburner-mono stoneburner-other stoneburner-plex stoneburner-testing stoneburner-vb stoneburner-vdr stoneburner-zfs-testing stoneburner-zfs" \
	-c "main" \
	-a "amd64 i386"
#	-a "amd64 armel armhf i386 powerpc"

################################################################################

exit 0

################################################################################
