#!/bin/bash

set -e
#set -x

DIRNAME=$(dirname "$0")

################################################################################
# Copy Repository

OUTDIR=${1:-"/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive/openmediavault"}
[ -d "$(dirname ${OUTDIR})" ] || exit 1

shift
INDIRS="$@"
[ -z "${INDIRS}" ] && exit 1

################################################################################

${DIRNAME}/copy_packages \
	-d "${OUTDIR}" \
	-i "${INDIRS}" \
	-n "openmediavault" \
	-s "stoneburner" \
	-c "main" \
	-a "amd64 i386" \
	-r

${DIRNAME}/copy_packages \
	-d "${OUTDIR}" \
	-i "${INDIRS}" \
	-n "openmediavault" \
	-s "stoneburner" \
	-c "main" \
	-k "testing" \
	-a "amd64 i386"

${DIRNAME}/copy_packages \
	-d "${OUTDIR}" \
	-i "${INDIRS}" \
	-n "openmediavault" \
	-s "stoneburner" \
	-c "testing" \
	-a "amd64 i386"

################################################################################

exit 0

################################################################################
