#!/bin/bash

set -e
#set -x

DIRNAME=$(dirname "$0")

################################################################################
# Copy Repository

OUTDIR=${1:-"/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive_input/openmediavault"}
[ -d "$(dirname ${OUTDIR})" ] || exit 1

################################################################################

${DIRNAME}/mirror_repository \
	-d "${OUTDIR}" \
	-u "http://packages.openmediavault.org/public" \
	-s "stoneburner" \
	-c "main" \
	-a "amd64 i386"
#	-a "amd64 armel armhf i386 powerpc"

################################################################################

exit 0

################################################################################
