#!/bin/bash

set -e
#set -x

DIRNAME=$(dirname "$0")

################################################################################
# Copy Repository

OUTDIR=${1:-"/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive"}
[ -d "$(dirname ${OUTDIR})" ] || exit 1

${DIRNAME}/update_mirror "${OUTDIR}"
${DIRNAME}/update_build "${OUTDIR}"
${DIRNAME}/update_copy "${OUTDIR}"
${DIRNAME}/update_debarchive "${OUTDIR}"

################################################################################

exit 0

################################################################################
