#!/bin/bash

set -e
#set -x

DIRNAME=$(dirname "$0")

################################################################################
# Copy Repository

OUTDIR=${1:-"/media/5fd18e51-966f-4664-b9cf-999c23d2855f/debarchive_build"}
[ -d "$(dirname ${OUTDIR})" ] || exit 1

${DIRNAME}/openmediavault_build "${OUTDIR}/openmediavault-build"
${DIRNAME}/omvextras_build "${OUTDIR}/omvextras-build"

################################################################################

exit 0

################################################################################
